name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: woocommerce-printnode-mpdf
        path: |
          ..
          !./**/.git/
          !./**/.github/
          !./**/ttfonts/AboriginalSansREGULAR.ttf
          !./**/ttfonts/Abyssinica_SIL.ttf
          !./**/ttfonts/Aegean.otf
          !./**/ttfonts/Aegyptus.otf
          !./**/ttfonts/Akkadian.otf
          !./**/ttfonts/ayar.ttf
          !./**/ttfonts/damase_v.2.ttf
          !./**/ttfonts/DBSILBR.ttf
          !./**/ttfonts/Dhyana-Bold.ttf
          !./**/ttfonts/DhyanaOFL.txt
          !./**/ttfonts/Dhyana-Regular.ttf
          !./**/ttfonts/FreeMonoBoldOblique.ttf
          !./**/ttfonts/FreeMonoBold.ttf
          !./**/ttfonts/FreeMonoOblique.ttf
          !./**/ttfonts/FreeMono.ttf
          !./**/ttfonts/FreeSansBoldOblique.ttf
          !./**/ttfonts/FreeSansBold.ttf
          !./**/ttfonts/FreeSansOblique.ttf
          !./**/ttfonts/FreeSans.ttf
          !./**/ttfonts/FreeSerifBoldItalic.ttf
          !./**/ttfonts/FreeSerifBold.ttf
          !./**/ttfonts/FreeSerifItalic.ttf
          !./**/ttfonts/FreeSerif.ttf
          !./**/ttfonts/Jomolhari-OFL.txt
          !./**/ttfonts/Jomolhari.ttf
          !./**/ttfonts/kaputaunicode.ttf
          !./**/ttfonts/KhmerOFL.txt
          !./**/ttfonts/KhmerOS.ttf
          !./**/ttfonts/lannaalif-v1-03.ttf
          !./**/ttfonts/Lateef
          !./**/ttfonts/LateefRegOT.ttf
          !./**/ttfonts/LohitKannadaOFL.txt
          !./**/ttfonts/Lohit-Kannada.ttf
          !./**/ttfonts/ocrb10.ttf
          !./**/ttfonts/ocrbinfo.txt
          !./**/ttfonts/Padauk-book.ttf
          !./**/ttfonts/Pothana2000.ttf
          !./**/ttfonts/Quivira.otf
          !./**/ttfonts/SundaneseUnicode-1.0.5.ttf
          !./**/ttfonts/Sun-ExtA.ttf
          !./**/ttfonts/Sun-ExtB.ttf
          !./**/ttfonts/SyrCOMEdessa_license.txt
          !./**/ttfonts/SyrCOMEdessa.otf
          !./**/ttfonts/TaameyDavidCLM-LICENSE.txt
          !./**/ttfonts/TaameyDavidCLM-Medium.ttf
          !./**/ttfonts/TaiHeritagePro.ttf
          !./**/ttfonts/TharlonOFL.txt
          !./**/ttfonts/Tharlon-Regular.ttf
          !./**/ttfonts/Uthman.otf
          !./**/ttfonts/XW
          !./**/ttfonts/ZawgyiOne.ttf

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
